-- Migración: tablas Ingresos y Facturación a Minoristas.
-- Idempotente — seguro de re-ejecutar.
--
-- Superset de columnas: incluye TODO lo que trae el scraper en vivo
-- (SportCenter-Reportes/) más los campos exclusivos del archivo histórico
-- (mayorista, emp, ing_sal, tipo_mov) que el ERP ya no expone en el export
-- actual — se guardan igual por contexto, pero la interfaz solo muestra las
-- columnas "estándar" (las del reporte actual).
--
-- Dedup por clave natural de documento (mismo formato en histórico y en
-- vivo): ser_num en facturación, codigo_interno en ingresos. Permite cargar
-- el histórico completo (que se solapa con lo ya scrapeado) sin duplicar, y
-- que "Sincronizar" solo agregue lo nuevo con ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS facturacion (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ser_num           TEXT NOT NULL UNIQUE,   -- SER-NUM (histórico) / N°DCTO (scraper), ej. "FJ01-4340"
  codigo            TEXT,                   -- solo scraper, ej. "V00029153"
  tienda            TEXT,                   -- solo scraper, ej. "J"
  tipo_comprobante  TEXT,                   -- COMPROBANTE (histórico) / DCTO (scraper), ej. "FACTURA"
  cliente           TEXT,                   -- MINORISTA (histórico) / CLIENTE (scraper)
  mayorista         TEXT,                   -- solo histórico
  fecha             TEXT NOT NULL,          -- ISO YYYY-MM-DD
  moneda            TEXT,
  subtotal          DOUBLE PRECISION,
  dscto             DOUBLE PRECISION,
  not_cre           DOUBLE PRECISION,
  bi                DOUBLE PRECISION,
  igv               DOUBLE PRECISION,
  total             DOUBLE PRECISION NOT NULL,
  efectivo          DOUBLE PRECISION,
  tarjeta           DOUBLE PRECISION,
  transferencia     DOUBLE PRECISION,
  detalle_tarjeta   TEXT,
  vendedor          TEXT,
  nc                TEXT,
  fuente            TEXT NOT NULL CHECK (fuente IN ('historico', 'erp')),
  imported_at       TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS ingresos (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_interno TEXT NOT NULL UNIQUE,   -- CODIGO (histórico) / CÓDIGO INTERNO (scraper), ej. "C001538"
  emp            TEXT,                   -- solo histórico
  almacen        TEXT,                   -- ALM (histórico) / ALMC (scraper)
  ing_sal        TEXT,                   -- solo histórico
  tipo_mov       TEXT,                   -- solo histórico
  serie_numero   TEXT,                   -- N° DCTO (histórico) / SERIE-NÚMERO (scraper)
  emision        TEXT NOT NULL,          -- ISO YYYY-MM-DD
  moneda         TEXT,
  importe        DOUBLE PRECISION,       -- solo histórico (monto único, sin desglose)
  subtotal       DOUBLE PRECISION,       -- solo scraper
  igv            DOUBLE PRECISION,       -- solo scraper
  dscto          DOUBLE PRECISION,       -- solo scraper
  total          DOUBLE PRECISION,       -- solo scraper
  ruc            TEXT,
  proveedor      TEXT,
  cmpl           TEXT,                   -- solo scraper
  mcdr           TEXT,                   -- solo scraper
  ord_compra     TEXT,                   -- solo scraper
  fuente         TEXT NOT NULL CHECK (fuente IN ('historico', 'erp')),
  imported_at    TEXT NOT NULL DEFAULT now_text()
);

CREATE INDEX IF NOT EXISTS idx_facturacion_fecha   ON facturacion(fecha);
CREATE INDEX IF NOT EXISTS idx_facturacion_cliente ON facturacion(cliente);
CREATE INDEX IF NOT EXISTS idx_ingresos_emision    ON ingresos(emision);
CREATE INDEX IF NOT EXISTS idx_ingresos_proveedor  ON ingresos(proveedor);

-- sync_log.tipo solo admitía 'stock'/'ventas' — se amplía para estos 2 reportes.
ALTER TABLE sync_log DROP CONSTRAINT IF EXISTS sync_log_tipo_check;
ALTER TABLE sync_log ADD CONSTRAINT sync_log_tipo_check
  CHECK (tipo IN ('stock', 'ventas', 'ingresos', 'facturacion'));

-- Módulos del sidebar (orden tras Análisis=10).
INSERT INTO modules (id, nombre, ruta, descripcion, orden) VALUES
  ('ingresos',    'Ingresos',    '/admin/ingresos',    NULL, 11),
  ('facturacion', 'Facturación', '/admin/facturacion', NULL, 12)
ON CONFLICT (id) DO NOTHING;
