-- Reportes de comisiones Minorista sincronizados desde VE/VERMAMI.
CREATE TABLE IF NOT EXISTS comisiones_ventas (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_venta           TEXT NOT NULL,
  codigo_venta          TEXT NOT NULL,
  comprobante_serie     TEXT,
  comprobante_numero    TEXT,
  codigo_barras         TEXT,
  codigo_universal      TEXT,
  modelo                TEXT,
  marca                 TEXT,
  grupo                 TEXT,
  categoria             TEXT,
  color                 TEXT,
  talla                 TEXT,
  precio_compra         DOUBLE PRECISION,
  precio_lista          DOUBLE PRECISION,
  precio_venta          DOUBLE PRECISION NOT NULL DEFAULT 0,
  tienda                TEXT,
  usuario               TEXT,
  promocion_aplicada    DOUBLE PRECISION,
  sincronizado_at       TEXT NOT NULL DEFAULT now_text(),
  UNIQUE (codigo_venta, codigo_barras, comprobante_serie, comprobante_numero)
);

CREATE INDEX IF NOT EXISTS idx_comisiones_fecha ON comisiones_ventas(fecha_venta);
CREATE INDEX IF NOT EXISTS idx_comisiones_usuario_fecha ON comisiones_ventas(usuario, fecha_venta);

CREATE TABLE IF NOT EXISTS comisiones_sync_log (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inicio    TEXT NOT NULL,
  fecha_fin       TEXT NOT NULL,
  filas           INTEGER NOT NULL,
  ejecutado_at    TEXT NOT NULL DEFAULT now_text(),
  ejecutado_by    TEXT REFERENCES users(id)
);
