-- Schema PostgreSQL de Stock Sport Center.
-- Traducción 1:1 de db/schema.sql + migraciones 001–004 (SQLite/Turso → PostgreSQL).
-- Idempotente: seguro de re-ejecutar. Aplicar con: node apply-migration.mjs db/schema_postgres.sql
--
-- Decisiones de tipo (ver plan de migración):
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--       (BY DEFAULT permite insertar ids explícitos en la migración de datos)
--   REAL (precios/importes)            -> DOUBLE PRECISION (pg lo devuelve como number JS,
--                                         a diferencia de numeric que llega como string)
--   INTEGER booleano (activo, etc.)    -> se mantiene INTEGER (el código pasa 1/0)
--   TEXT DEFAULT (datetime('now'))     -> TEXT DEFAULT now_text()  (mismo formato UTC)

-- Réplica del formato exacto de SQLite datetime('now'): 'YYYY-MM-DD HH:MM:SS' en UTC.
CREATE OR REPLACE FUNCTION now_text() RETURNS text LANGUAGE sql AS $$
  SELECT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS');
$$;

CREATE TABLE IF NOT EXISTS tiendas (
  id                     TEXT PRIMARY KEY,
  nombre                 TEXT NOT NULL UNIQUE,
  excluida_actualizacion INTEGER NOT NULL DEFAULT 0,
  created_at             TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY,
  username   TEXT NOT NULL UNIQUE,
  email      TEXT UNIQUE,
  password   TEXT NOT NULL,
  nombre     TEXT NOT NULL,
  rol        TEXT NOT NULL CHECK (rol IN ('client', 'admin', 'administrador_general')),
  tienda_id  TEXT REFERENCES tiendas(id) ON DELETE SET NULL,
  activo     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS modules (
  id          TEXT PRIMARY KEY,
  nombre      TEXT NOT NULL,
  ruta        TEXT NOT NULL,
  descripcion TEXT,
  orden       INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS admin_modules (
  user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, module_id)
);

CREATE TABLE IF NOT EXISTS vendedores (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario    TEXT,
  nombre     TEXT NOT NULL,
  codigo     TEXT NOT NULL UNIQUE,
  tienda_id  TEXT REFERENCES tiendas(id) ON DELETE CASCADE,
  activo     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS producto_imagenes (
  cod_universal TEXT PRIMARY KEY,
  imagen_url    TEXT NOT NULL,
  source        TEXT NOT NULL CHECK (source IN ('archivo', 'sistema')),
  updated_at    TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS sync_log (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo         TEXT NOT NULL CHECK (tipo IN ('stock', 'ventas')),
  filas        INTEGER,
  ejecutado_at TEXT NOT NULL DEFAULT now_text(),
  ejecutado_by TEXT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS productos (
  cod_universal TEXT NOT NULL,
  genero        TEXT NOT NULL,
  marca         TEXT,
  modelo        TEXT,
  categoria     TEXT,
  grupo         TEXT,
  color         TEXT,
  precio_lista  DOUBLE PRECISION,
  descuento     DOUBLE PRECISION NOT NULL DEFAULT 0,
  stock_total   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (cod_universal, genero)
);

CREATE TABLE IF NOT EXISTS variantes (
  cod_barras    TEXT PRIMARY KEY,
  cod_universal TEXT NOT NULL,
  genero        TEXT NOT NULL,
  talla         TEXT,
  alm_izq       TEXT,
  alm_der       TEXT,
  cod_prod      TEXT,
  precio_compra DOUBLE PRECISION,
  ingreso_fecha TEXT,
  FOREIGN KEY (cod_universal, genero) REFERENCES productos(cod_universal, genero) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lotes (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado       TEXT NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador', 'publicado', 'cerrado')),
  created_at   TEXT NOT NULL DEFAULT now_text(),
  created_by   TEXT REFERENCES users(id),
  published_at TEXT,
  published_by TEXT REFERENCES users(id),
  closed_at    TEXT,
  closed_by    TEXT REFERENCES users(id),
  resanado_at  TEXT,
  resanado_by  TEXT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS lote_lineas (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id            INTEGER NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
  cod_universal      TEXT NOT NULL,
  genero             TEXT NOT NULL,
  descuento_antes    DOUBLE PRECISION NOT NULL,
  descuento_nuevo    DOUBLE PRECISION NOT NULL,
  snap_marca         TEXT,
  snap_modelo        TEXT,
  snap_categoria     TEXT,
  snap_color         TEXT,
  snap_precio_lista  DOUBLE PRECISION,
  snap_precio_compra DOUBLE PRECISION,
  editado_at         TEXT NOT NULL DEFAULT now_text(),
  UNIQUE (lote_id, cod_universal, genero)
);

CREATE TABLE IF NOT EXISTS lote_exclusiones (
  lote_id     INTEGER NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
  tienda_id   TEXT    NOT NULL REFERENCES tiendas(id) ON DELETE CASCADE,
  excluida_at TEXT    NOT NULL DEFAULT now_text(),
  excluida_by TEXT    REFERENCES users(id),
  PRIMARY KEY (lote_id, tienda_id)
);

CREATE TABLE IF NOT EXISTS confirmaciones (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id        INTEGER NOT NULL REFERENCES lotes(id) ON DELETE CASCADE,
  tienda_id      TEXT NOT NULL REFERENCES tiendas(id) ON DELETE CASCADE,
  cod_universal  TEXT NOT NULL,
  genero         TEXT NOT NULL,
  estado         TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'confirmado', 'rechazado')),
  resuelto_at    TEXT,
  vendedor_id    INTEGER REFERENCES vendedores(id),
  codigo_usado   TEXT,
  motivo_rechazo TEXT,
  UNIQUE (lote_id, tienda_id, cod_universal, genero)
);

-- Tabla de hechos: una fila por unidad vendida (ver migración 001).
CREATE TABLE IF NOT EXISTS ventas (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_barras    TEXT NOT NULL UNIQUE,   -- serial por unidad → clave de dedup
  cod_universal TEXT,
  genero        TEXT,
  fecha_venta   TEXT NOT NULL,          -- ISO YYYY-MM-DD
  ingreso_fecha TEXT,
  almacen       TEXT,
  marca         TEXT,
  modelo        TEXT,
  categoria     TEXT,
  grupo         TEXT,
  color         TEXT,
  talla         TEXT,
  precio_compra DOUBLE PRECISION,
  precio_lista  DOUBLE PRECISION,
  importe       DOUBLE PRECISION,
  imported_at   TEXT NOT NULL DEFAULT now_text()
);

CREATE TABLE IF NOT EXISTS rate_limits (
  clave    TEXT PRIMARY KEY,
  intentos INTEGER NOT NULL DEFAULT 1,
  reset_at BIGINT  NOT NULL          -- epoch ms (Date.now())
);

-- ── Índices ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_variantes_producto      ON variantes(cod_universal, genero);
CREATE INDEX IF NOT EXISTS idx_variantes_alm_izq        ON variantes(alm_izq);
CREATE INDEX IF NOT EXISTS idx_variantes_alm_der        ON variantes(alm_der);
CREATE INDEX IF NOT EXISTS idx_lineas_lote              ON lote_lineas(lote_id);
CREATE INDEX IF NOT EXISTS idx_conf_lote                ON confirmaciones(lote_id);
CREATE INDEX IF NOT EXISTS idx_conf_tienda_estado       ON confirmaciones(tienda_id, estado);
CREATE INDEX IF NOT EXISTS idx_productos_marca_modelo   ON productos(marca, modelo);
CREATE INDEX IF NOT EXISTS idx_ventas_producto          ON ventas(cod_universal, genero);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha             ON ventas(fecha_venta);
CREATE INDEX IF NOT EXISTS idx_ventas_marca             ON ventas(marca);
CREATE INDEX IF NOT EXISTS idx_ventas_categoria         ON ventas(categoria);
CREATE INDEX IF NOT EXISTS idx_ventas_ingreso           ON ventas(ingreso_fecha);
-- Índices de rendimiento (migración 004, aplicados en Turso).
CREATE INDEX IF NOT EXISTS idx_variantes_antigedad      ON variantes(cod_universal, genero, ingreso_fecha);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha_producto    ON ventas(fecha_venta, cod_universal, genero);

-- ── Seed de módulos del sidebar (datos de configuración) ─────────────────────
INSERT INTO modules (id, nombre, ruta, descripcion, orden) VALUES
  ('dashboard',    'Dashboard',        '/admin',                        NULL, 1),
  ('productos',    'Productos',        '/admin/productos',              NULL, 2),
  ('actualizacion','Actualización',    '/admin/actualizacion',          NULL, 3),
  ('registro',     'Registro Cambios', '/admin/actualizacion-updates',  NULL, 4),
  ('tiendas',      'Tiendas',          '/admin/gestion/tiendas',        NULL, 5),
  ('usuarios',     'Usuarios',         '/admin/gestion/usuarios',       NULL, 6),
  ('credenciales', 'Credenciales',     '/admin/gestion/credenciales',   NULL, 7),
  ('reposicion',   'Reposición',       '/admin/reposicion',             NULL, 8),
  ('utils',        'Utilidades',       '/admin/utils',                  NULL, 9),
  ('analisis',     'Análisis',         '/admin/analisis',
   'Rotación, stock muerto y tendencias de ventas', 10)
ON CONFLICT (id) DO NOTHING;

-- Migración: la tienda deja de ser obligatoria al crear un vendedor (credencial
-- global válida en cualquier tienda hasta que se le asigne una). Idempotente:
-- no falla si la columna ya es nullable.
ALTER TABLE vendedores ALTER COLUMN tienda_id DROP NOT NULL;

-- Migración: usuario del vendedor (para BDs creadas antes de agregar la columna).
ALTER TABLE vendedores ADD COLUMN IF NOT EXISTS usuario TEXT;
